### ISSUE TITLE
Remove account id

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#101]
It isn't used.

```
wasapi_providers:
  ait:
    name: Archive-It
    baseurl: https://archive-it.org/
    authurl: https://archive-it.org/login
    accounts:
      ua:
        accountid: 1 <----
        username: user
        password: pass
```
