### ISSUE TITLE
Correctly model providers / accounts / collections

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was-registrar-app#97]
Currently, the model is a WASAPI provider has one or more accounts, e.g.:
```
wasapi_providers:
  ait:
    name: Archive-It
    baseurl: https://archive-it.org/
    authurl: https://archive-it.org/login
    accounts:
      ua:
        accountid: 1
        username: user
        password: pass
      history:
        accountid: 2
        username: user2
        password: pass2
```

It should be a WASAPI provider has one or more accounts and an account has one or more collections, e.g.:
```
wasapi_providers:
  ait:
    name: Archive-It
    baseurl: https://archive-it.org/
    authurl: https://archive-it.org/login
    accounts:
      ua:
        username: user
        password: pass
        collections:
          - alumni
          - departments
```

This will require changes to the collection model so that WASAPI provider, account, and collection is recorded. The edit screen will need to be updated accordingly. And the fetch job will need to be fixed to make the appropriate request.
